CREATE TABLE IF NOT EXISTS PURCHASE (
    id INT NOT NULL AUTO_INCREMENT,
    amount DOUBLE NOT NULL,
    currency VARCHAR(255) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS PURCHASED_PRODUCT (
    id INT NOT NULL AUTO_INCREMENT,
    purchase_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    reference VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    price DOUBLE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (purchase_id) REFERENCES PURCHASE(id)
);